/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class calculadora */

#ifndef _Included_calculadora
#define _Included_calculadora
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     calculadora
 * Method:    sumaC
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_calculadora_sumaC
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     calculadora
 * Method:    restaC
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_calculadora_restaC
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     calculadora
 * Method:    multC
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_calculadora_multC
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     calculadora
 * Method:    divC
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_calculadora_divC
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
